
---

apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep
---

apiVersion: v1
kind: Namespace
metadata:
  name: linkerd
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep

---

apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/resource-policy": keep
