apiVersion: v2
name: k8s-test-rig
description: A Helm chart for Kubernetes

type: application

# This is the chart version. 
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: https://kubernetes.github.io/ingress-nginx
  - name: linkerd-crds
    version: "2024.11.8"
    repository: https://helm.linkerd.io/edge
  - name: linkerd-control-plane
    version: "2024.11.8"
    repository: https://helm.linkerd.io/edge
  #- name: argo-cd
  #  version: "7.7.11"
  #  repository: https://argoproj.github.io/argo-helm
  - name: external-secrets
    version: "0.9.8"
    repository: https://charts.external-secrets.io
  # TODO: switch with Gardener external-dns-management after implementing PowerDNS provider for gardener
  - name: external-dns
    version: "1.15.0"
    repository: https://kubernetes-sigs.github.io/external-dns/
  - name: cert-manager
    version: "1.16.2"
    repository: https://charts.jetstack.io
  - name: loki
    version: "6.20.0-weekly.229"
    repository: oci://ghcr.io/grafana/helm-charts
  - name: "promtail"
    repository: https://grafana.github.io/helm-charts
    version: "^6.16.3"
  #- name: prometheus-operator-crds
  #  version: "17.0.2"
  #  repository: https://prometheus-community.github.io/helm-charts
  - name: kube-prometheus-stack
    version: "67.4.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana-operator
    version: "v5.15.1"
    repository: oci://ghcr.io/grafana/helm-charts
  - name: vault
    version: "0.26.1"
    repository: https://helm.releases.hashicorp.com
