apiVersion: v2
name: k8s-test-rig
description: A Helm chart for Kubernetes

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 0.1.0

# This is the version number of the application being deployed. This version number should be
# incremented each time you make changes to the application. Versions are not expected to
# follow Semantic Versioning. They should reflect the version the application is using.
# It is recommended to use it with quotes.
appVersion: "0.1.0"

dependencies:
  - name: ingress-nginx
    version: "4.8.3"
    repository: https://kubernetes.github.io/ingress-nginx
  - name: linkerd-crds
    version: "1.8.0"
    repository: https://helm.linkerd.io/stable
  - name: linkerd-control-plane
    version: "1.16.3"
    repository: https://helm.linkerd.io/stable
  - name: external-secrets
    version: "0.9.8"
    repository: https://charts.external-secrets.io
  # TODO: switch with Gardener external-dns-management after implementing PowerDNS provider for gardener
  - name: external-dns
    version: "1.13.1"
    repository: https://kubernetes-sigs.github.io/external-dns/
  - name: cert-manager
    version: "1.13.2"
    repository: https://charts.jetstack.io
  - name: loki-stack
    version: "2.9.11"
    repository: https://grafana.github.io/helm-charts
  - name: "promtail"
    repository: "https://grafana.github.io/helm-charts"
    version: "^6.15.3"
  - name: kube-prometheus-stack
    version: "52.1.0"
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana-operator
    version: "v5.4.2"
    repository: oci://ghcr.io/grafana-operator/helm-charts
  - name: vault
    version: "0.26.1"
    repository: https://helm.releases.hashicorp.com
